name: victortang
favicon: null
layout_spectrum: 0.8050983548164368
typography_spectrum: 0.5324203441850841
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9463480112608522
  lightness: 0.524955369764939
  saturation: 0.640868169022724
  rhythmicContrast: 0.4693492071237415
purpose: []
